mdai-operator:
  controllerManager:
    manager:
      env:
        otelSdkDisabled: "true"

mdai-gateway:
  otelSdkDisabled: "true"

mdai-s3-logs-reader:
  enabled: false

valkey:
  enabled: true
  auth:
    enabled: true

nats:
  config:
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: "/data/jetstream"
        pvc:
          enabled: true
          storageClassName: "standard"
          size: 1Gi
          apiVersion: v1
          kind: PersistentVolumeClaim
