persistentStorage:
  nats:
    pv:
      # Specifies whether a PersistentVolumes should be created
      create: true
      # Deployment platform: can be either "aws" or "kind" (for local development))
      platform: kind
      # directory where data will be stored if deployment platform is "kind"
      localPath: "/workspaces/work/kind/data"

mdai-operator:
  controllerManager:
    manager:
      env:
        otelSdkDisabled: "true"

mdai-gateway:
  otelSdkDisabled: "true"

mdai-s3-logs-reader:
  enabled: false

valkey:
  enabled: true
  auth:
    enabled: true

nats:
  config:
    jetstream:
      enabled: true
      fileStore:
        enabled: true
        dir: "/data/jetstream"
        pvc:
          enabled: true
          storageClassName: "mdai"
          size: 1Gi