apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-name-params
  namespace: mdai
data:
  HUB_NAME: mdaihub-team-payments
  # Name of the generated variables ConfigMap that the collector should envFrom.
  # (If your operator uses a different naming convention, change this once per team.)
  HUB_VARS_CM: mdaihub-team-payments-variables
